name: Actions 😎

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2.3.2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2.1.1
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        id: testRunner
        uses: webbertakken/unity-test-runner@v1.6
        with:
          customParameters: '-nographics'
          unityVersion: 2020.1.0f1

      # Upload test results
      - uses: actions/upload-artifact@v2
        with:
          name: Test results (all modes)
          path: ${{ steps.testRunner.outputs.artifactsPath }}

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v1.2
        with:
          customParameters: '-nographics'
          allowDirtyBuild: true
          unityVersion: 2020.1.0f1
          targetPlatform: StandaloneWindows64

      # Upload build results
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
